### PR TITLE
Bug: dashboard custom date empty menu

### LINKED ISSUE #1022: [BUG - Dashboard] After selecting the custom date in the asset graph, the next clean clears the menu
## Reproduce steps

1. Go to the Dashboard
2. Click "All Time" dropdown -> custom -> pick date -> apply
3. Click "All Time" dropdown - the menu will be empty

image

## Expected Results

Menu should not be empty

## Actual Results

menu is empty

### PR DESCRIPTION
**Pull request by astra1**
# Description

https://user-images.githubusercontent.com/4422785/228889486-a5d3e552-aadf-4e76-b5e4-8fb30f211d58.mp4

Fixes #1022

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

### CODE REVIEW

File: webapp/src/app/shared/dropdown/dropdown.component.ts [hunk 1]
```diff
@@ -102,8 +102,11 @@ export class DropdownComponent implements OnChanges {
       return /^\d/.test(option);
   }
 
-  capitalizeFirstLetter(option:string){
+  capitalizeFirstLetter(option: string | unknown[]) {
```
Comment (plyubich) [inline webapp/src/app/shared/dropdown/dropdown.component.ts:105]: this is the fix
